#pragma once
#include "utils.h"

typedef enum {
    // SYMBOLS
    TOKEN_PLUS, TOKEN_MINUS,
    TOKEN_STAR, TOKEN_SLASH,
    TOKEN_EQ,
    TOKEN_PAREN_LEFT, TOKEN_PAREN_RIGHT,
    TOKEN_BRACE_LEFT, TOKEN_BRACE_RIGHT,
    TOKEN_CURLY_LEFT, TOKEN_CURLY_RIGHT,
    TOKEN_BANG, TOKEN_AT,
    TOKEN_HASH, TOKEN_DOLLAR,
    TOKEN_PERCENT,
    TOKEN_QUOTE, TOKEN_DOUBLE_QUOTE,
    TOKEN_QUESTION,
    TOKEN_COMMA, TOKEN_SEMI, TOKEN_COLON,
    TOKEN_DOT,

    // OPERATORS
    TOKEN_PLUS_PLUS, TOKEN_PLUS_EQ,
    TOKEN_MINUS_MINUS, TOKEN_MINUS_EQ,
    TOKEN_MULTI_EQ, TOKEN_DIV_EQ,
    TOKEN_EQ_EQ, TOKEN_NOT_EQ,
    TOKEN_LT, TOKEN_LT_EQ,
    TOKEN_GT, TOKEN_GT_EQ,
    TOKEN_POW, TOKEN_XOR,
    TOKEN_LOGICAL_AND, TOKEN_LOGICAL_OR,
    TOKEN_BIT_OR, TOKEN_BIT_OR_EQ,
    TOKEN_BIT_AND, TOKEN_BIT_AND_EQ,
    TOKEN_SHIFT_LEFT, TOKEN_SHIFT_LEFT_EQ,
    TOKEN_SHIFT_RIGHT, TOKEN_SHIFT_RIGHT_EQ,
    TOKEN_BIT_NOT, TOKEN_XOR_EQ,

    // KEYWORDS
    TOKEN_WHILE, TOKEN_FOR,
    TOKEN_BREAK, TOKEN_RETURN,
    TOKEN_CONTINUE,
    TOKEN_IF, TOKEN_ELSE,
    TOKEN_IMPORT, TOKEN_STATIC,
    TOKEN_DEFER, TOKEN_COMPTIME,
    TOKEN_STRUCT, TOKEN_TYPE,
    TOKEN_CONST, TOKEN_ENUM,
    TOKEN_TRUE, TOKEN_FALSE,

    // TYPES
    TOKEN_CHAR,
    TOKEN_INT, TOKEN_FLOAT,
    TOKEN_BOOL,
    TOKEN_VOID, TOKEN_NULL,

    // LITERALS
    TOKEN_LIT_STR, TOKEN_LIT_CHAR,
    TOKEN_LIT_INT, TOKEN_LIT_FLOAT,
    TOKEN_IDENT,

    // OTHER
    TOKEN_EOF,
    TOKEN_UNKNOWN,
    TOKEN_COUNT,
} TokenType;

typedef enum {
    TYPE_VOID, TYPE_NULL,
    TYPE_INT, TYPE_FLOAT,
    TYPE_CHAR,
    TYPE_BOOL, TYPE_CUSTOM,
} TypeKind;

typedef struct {
    TypeKind kind;
    StringStream name;
    int pointer_depth;
} DataType;

typedef struct {
    TokenType type;
    StringStream view;
    size_t line;
    size_t col;
} Token;

// NODES
typedef struct Node {
    bool _export;
} Node;
